#Tomcat
server:
  port: 8989

#spring
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.160.156:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  profiles:
    active: prod

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.beyond233.jwtlearn.pojo

#自定义配置
auth:
  enable: true